=== jdempsey-au/pcgen-1/system/npcgen/classdata/classdata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by A Divinsk (None) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="stats">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="stat" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="stat">
		<xs:complexType>
			<xs:attribute name="weight" type="xs:integer" use="optional" default="1"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="skills">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="skill" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="skill">
		<xs:complexType>
			<xs:attribute name="weight" type="xs:integer" use="optional" default="1"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="class_data">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="class" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="game_mode" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="stats"/>
				<xs:sequence minOccurs="0">
					<xs:element ref="skills" minOccurs="0"/>
					<xs:element ref="abilities" minOccurs="0"/>
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="key" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ability">
		<xs:complexType>
			<xs:attribute name="weight" type="xs:integer" use="optional" default="1"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="abilities">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ability" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="category" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jdempsey-au/pcgen-1/system/npcgen/classdata/classdata35.xml
<?xml version="1.0" encoding="UTF-8"?>
<class_data game_mode="35e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="classdata.xsd">
	<class key="Barbarian">
		<stats>
			<stat value="STR" weight="9"/>
			<stat value="CON" weight="8"/>
			<stat value="DEX" weight="7"/>
			<stat value="CHA" weight="3"/>
			<stat value="INT" weight="2"/>
			<stat value="WIS" weight="1"/>
		</stats>
		<skills>
			<skill value="Balance" weight="3"/>
			<skill value="Climb" weight="30"/>
			<skill value="Concentration" weight="0"/>
			<skill value="Control Shape" weight="0"/>
			<skill value="TYPE.Craft" weight="10"/>
			<skill value="Decipher Script" weight="0"/>
			<skill value="Handle Animal" weight="18"/>
			<skill value="Heal" weight="10"/>
			<skill value="Hide" weight="15"/>
			<skill value="Intimidate" weight="25"/>
			<skill value="Jump" weight="40"/>
			<skill value="Knowledge (Geography)" weight="10"/>
			<skill value="Knowledge (History)" weight="5"/>
			<skill value="Knowledge (Nature)" weight="10"/>
			<skill value="Listen" weight="40"/>
			<skill value="Literacy" weight="5"/>
			<skill value="Move Silently" weight="15"/>
			<skill value="TYPE.Perform" weight="1"/>
			<skill value="TYPE.Profession" weight="5"/>
			<skill value="Ride" weight="35"/>
			<skill value="Spot" weight="20"/>
			<skill value="Survival" weight="45"/>
			<skill value="Swim" weight="30"/>
			<skill value="Use Rope" weight="5"/>
			<skill value="Autohypnosis" weight="0"/>
			<skill value="*" weight="1"/>
		</skills>
		<abilities category="FEAT">
			<ability value="Acrobatic" weight="8"/>
			<ability value="Agile" weight="4"/>
			<ability value="Alertness" weight="20"/>
			<ability value="Animal Affinity" weight="4"/>
			<ability value="Armor Proficiency (Heavy)" weight="2"/>
			<ability value="Armor Proficiency (Light)" weight="0"/>
			<ability value="Armor Proficiency (Medium)" weight="0"/>
			<ability value="Athletic" weight="8"/>
			<ability value="Augment Summoning" weight="0"/>
			<ability value="Blind Fight" weight="20"/>
			<ability value="Brew Potion" weight="0"/>
			<ability value="Cleave" weight="20"/>
			<ability value="Combat Casting" weight="0"/>
			<ability value="Combat Expertise" weight="2"/>
			<ability value="Combat Reflexes" weight="20"/>
			<ability value="TYPE.ItemCreation" weight="0"/>
			<ability value="Deceitful" weight="2"/>
			<ability value="Deflect Arrows" weight="2"/>
			<ability value="Deft Hands" weight="2"/>
			<ability value="Diehard" weight="8"/>
			<ability value="Diligent" weight="2"/>
			<ability value="Dodge" weight="16"/>
			<ability value="TYPE.Metamagic" weight="0"/>
			<ability value="Endurance" weight="20"/>
			<ability value="Eschew Materials" weight="0"/>
			<ability value="Exotic Weapon Proficiency" weight="4"/>
			<ability value="Extend Spell" weight="0"/>
			<ability value="Extra Turning" weight="0"/>
			<ability value="Far Shot" weight="2"/>
			<ability value="Forge Ring" weight="0"/>
			<ability value="Great Cleave" weight="20"/>
			<ability value="Great Fortitude" weight="8"/>
			<ability value="Greater Spell Focus" weight="0"/>
			<ability value="Greater Spell Penetration" weight="0"/>
			<ability value="Greater Two Weapon Fighting" weight="8"/>
			<ability value="Greater Weapon Focus" weight="8"/>
			<ability value="Greater Weapon Specialization" weight="0"/>
			<ability value="Heighten Spell" weight="0"/>
			<ability value="Improved Bull Rush" weight="8"/>
			<ability value="Improved Counterspell" weight="0"/>
			<ability value="Improved Critical" weight="8"/>
			<ability value="Improved Disarm" weight="2"/>
			<ability value="Improved Familiar" weight="0"/>
			<ability value="Improved Feint" weight="8"/>
			<ability value="Improved Grapple" weight="4"/>
			<ability value="Improved Initiative" weight="4"/>
			<ability value="Improved Overrun" weight="2"/>
			<ability value="Improved Precise Shot" weight="8"/>
			<ability value="Improved Shield Bash" weight="2"/>
			<ability value="Improved Sunder" weight="4"/>
			<ability value="Improved Trip" weight="2"/>
			<ability value="Improved Turning" weight="0"/>
			<ability value="Improved Two Weapon Fighting" weight="8"/>
			<ability value="Improved Unarmed Strike" weight="4"/>
			<ability value="Investigator" weight="2"/>
			<ability value="Iron Will" weight="8"/>
			<ability value="Leadership" weight="2"/>
			<ability value="Lightning Reflexes" weight="8"/>
			<ability value="Magical Aptitude" weight="0"/>
			<ability value="Manyshot" weight="2"/>
			<ability value="Martial Weapon Proficiency" weight="0"/>
			<ability value="Maximize Spell" weight="0"/>
			<ability value="Mobility" weight="8"/>
			<ability value="Mounted Archery" weight="2"/>
			<ability value="Mounted Combat" weight="4"/>
			<ability value="Natural Spell" weight="0"/>
			<ability value="Negotiator" weight="2"/>
			<ability value="Nimble Fingers" weight="2"/>
			<ability value="Persuasive" weight="8"/>
			<ability value="Point Blank Shot" weight="2"/>
			<ability value="Power Attack" weight="40"/>
			<ability value="Precise Shot" weight="2"/>
			<ability value="Quick Draw" weight="8"/>
			<ability value="Quicken Spell" weight="0"/>
			<ability value="Rapid Reload" weight="1"/>
			<ability value="Rapid Shot" weight="2"/>
			<ability value="Ride By Attack" weight="4"/>
			<ability value="Run" weight="20"/>
			<ability value="Scribe Scroll" weight="0"/>
			<ability value="Self Sufficient" weight="8"/>
			<ability value="Shield Proficiency" weight="0"/>
			<ability value="Shot on the Run" weight="2"/>
			<ability value="Silent Spell" weight="0"/>
			<ability value="Simple Weapon Proficiency" weight="0"/>
			<ability value="Skill Focus" weight="2"/>
			<ability value="Snatch Arrows" weight="2"/>
			<ability value="Spell Focus" weight="0"/>
			<ability value="Spell Mastery" weight="0"/>
			<ability value="Spell Penetration" weight="0"/>
			<ability value="Spirited Charge" weight="2"/>
			<ability value="Spring Attack" weight="2"/>
			<ability value="Stealthy" weight="8"/>
			<ability value="Still Spell" weight="0"/>
			<ability value="Stunning Fist" weight="2"/>
			<ability value="Toughness" weight="4"/>
			<ability value="Tower Shield Proficiency" weight="2"/>
			<ability value="Track" weight="8"/>
			<ability value="Trample" weight="4"/>
			<ability value="Two Weapon Fighting" weight="2"/>
			<ability value="Two Weapon Defense" weight="2"/>
			<ability value="Weapon Finesse" weight="2"/>
			<ability value="Weapon Focus" weight="8"/>
			<ability value="Weapon Specialization" weight="0"/>
			<ability value="Whirlwind Attack" weight="2"/>
			<ability value="Widen Spell" weight="0"/>
		</abilities>
	</class>
	<class key="Bard">
		<stats>
			<stat value="CHA" weight="9"/>
			<stat value="INT" weight="5"/>
			<stat value="DEX" weight="4"/>
			<stat value="CON" weight="3"/>
			<stat value="STR" weight="2"/>
			<stat value="WIS" weight="1"/>
		</stats>
		<skills>
			<skill value="Appraise" weight="15"/>
			<skill value="Balance" weight="10"/>
			<skill value="Bluff" weight="20"/>
			<skill value="Climb" weight="6"/>
			<skill value="Concentration" weight="15"/>
			<skill value="Control Shape" weight="0"/>
			<skill value="TYPE.Craft" weight="6"/>
			<skill value="Decipher Script" weight="25"/>
			<skill value="Diplomacy" weight="35"/>
			<skill value="Disguise" weight="25"/>
			<skill value="Escape Artist" weight="10"/>
			<skill value="Forgery" weight="9"/>
			<skill value="Gather Information" weight="40"/>
			<skill value="Hide" weight="15"/>
			<skill value="Intimidate" weight="10"/>
			<skill value="Jump" weight="6"/>
			<skill value="Knowledge (Arcana)" weight="8"/>
			<skill value="Knowledge (Architecture and Engineering)" weight="7"/>
			<skill value="Knowledge (Dungeoneering)" weight="7"/>
			<skill value="Knowledge (Geography)" weight="9"/>
			<skill value="Knowledge (History)" weight="11"/>
			<skill value="Knowledge (Local)" weight="11"/>
			<skill value="Knowledge (Nature)" weight="7"/>
			<skill value="Knowledge (Nobility and Royalty)" weight="11"/>
			<skill value="Knowledge (Religion)" weight="7"/>
			<skill value="Knowledge (The Planes)" weight="7"/>
			<skill value="Listen" weight="20"/>
			<skill value="Literacy" weight="0"/>
			<skill value="Move Silently" weight="15"/>
			<skill value="TYPE.Perform" weight="100"/>
			<skill value="TYPE.Profession" weight="9"/>
			<skill value="Sense Motive" weight="15"/>
			<skill value="Sleight of Hand" weight="15"/>
			<skill value="Speak Language" weight="11"/>
			<skill value="Spellcraft" weight="30"/>
			<skill value="Swim" weight="6"/>
			<skill value="Tumble" weight="8"/>
			<skill value="Use Magic Device" weight="30"/>
			<skill value="Autohypnosis" weight="0"/>
			<skill value="*" weight="1"/>
		</skills>
		<abilities category="FEAT">
			<ability value="Acrobatic" weight="2"/>
			<ability value="Agile" weight="2"/>
			<ability value="Alertness" weight="20"/>
			<ability value="Animal Affinity" weight="2"/>
			<ability value="Armor Proficiency (Heavy)" weight="1"/>
			<ability value="Armor Proficiency (Light)" weight="0"/>
			<ability value="Armor Proficiency (Medium)" weight="2"/>
			<ability value="Athletic" weight="2"/>
			<ability value="Augment Summoning" weight="8"/>
			<ability value="Blind Fight" weight="8"/>
			<ability value="Brew Potion" weight="16"/>
			<ability value="Cleave" weight="2"/>
			<ability value="Combat Casting" weight="20"/>
			<ability value="Combat Expertise" weight="8"/>
			<ability value="Combat Reflexes" weight="8"/>
			<ability value="Craft Construct" weight="2"/>
			<ability value="Craft Magic Arms and Armor" weight="8"/>
			<ability value="Craft Rod" weight="8"/>
			<ability value="Craft Staff" weight="8"/>
